const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pulse', {
  getUsage: () => ipcRenderer.invoke('usage:get'),
  generateHandoff: sessionFile => ipcRenderer.invoke('handoff:generate', sessionFile),
  copyHandoff: (text, meta) => ipcRenderer.invoke('handoff:copy', text, meta),
  generateBugCapsule: () => ipcRenderer.invoke('bug:generate'),
  copyBugCapsule: text => ipcRenderer.invoke('bug:copy', text),
  onBugReady: callback => ipcRenderer.on('bug:ready', (_, value) => callback(value)),
  getSystemStats: () => ipcRenderer.invoke('system:get'),
  onSystemStats: callback => ipcRenderer.on('system:update', (_, value) => callback(value)),
  onScreenshots: callback => ipcRenderer.on('screenshots:update', (_, value) => callback(value)),
  onUsage: callback => ipcRenderer.on('usage:update', (_, value) => callback(value)),
  onUsageError: callback => ipcRenderer.on('usage:error', (_, value) => callback(value)),
  listScreenshots: () => ipcRenderer.invoke('screenshots:list'),
  searchScreenshots: query => ipcRenderer.invoke('screenshots:search', query),
  favoriteScreenshot: (full, value) => ipcRenderer.invoke('screenshots:favorite', full, value),
  tagScreenshot: (full, tags) => ipcRenderer.invoke('screenshots:tags', full, tags),
  takeScreenshot: () => ipcRenderer.invoke('screenshots:take'),
  takeRegionScreenshot: () => ipcRenderer.invoke('screenshots:region'),
  openScreenshots: () => ipcRenderer.invoke('screenshots:open-folder'),
  openScreenshot: full => ipcRenderer.invoke('screenshots:open', full),
  copyScreenshot: full => ipcRenderer.invoke('screenshots:copy', full),
  saveScreenshotAs: full => ipcRenderer.invoke('screenshots:save-as', full),
  saveAnnotation: (full, dataUrl) => ipcRenderer.invoke('screenshots:save-annotation', full, dataUrl),
  deleteScreenshot: full => ipcRenderer.invoke('screenshots:delete', full),
  openDisk: name => ipcRenderer.invoke('system:open-disk', name),
  openWorkspace: full => ipcRenderer.invoke('system:open-workspace', full),
  minimize: () => ipcRenderer.invoke('window:minimize'),
  close: () => ipcRenderer.invoke('window:close'),
  toggleTop: value => ipcRenderer.invoke('window:toggle-top', value),
  setExpanded: value => ipcRenderer.invoke('window:set-expanded', value),
  setPeek: value => ipcRenderer.invoke('window:set-peek', value),
  getUiSettings: () => ipcRenderer.invoke('ui:get-settings'),
  setFontSize: value => ipcRenderer.invoke('ui:set-font-size', value),
  setManualFullscreen: value => ipcRenderer.invoke('window:set-manual-fullscreen', value),
  getManualImage: () => ipcRenderer.invoke('manual:get-image'),
  chooseManualImage: () => ipcRenderer.invoke('manual:choose-image'),
  resetManualImage: () => ipcRenderer.invoke('manual:reset-image'),
  getCompanion: () => ipcRenderer.invoke('companion:get'),
  generateDailyLetter: force => ipcRenderer.invoke('companion:generate-letter', force),
  saveCompanionSettings: settings => ipcRenderer.invoke('companion:settings', settings),
  saveRole: role => ipcRenderer.invoke('companion:save-role', role),
  selectRole: roleId => ipcRenderer.invoke('companion:select-role', roleId),
  deleteRole: roleId => ipcRenderer.invoke('companion:delete-role', roleId),
  importRole: () => ipcRenderer.invoke('companion:import-role'),
  exportRole: roleId => ipcRenderer.invoke('companion:export-role', roleId),
  saveShareCard: dataUrl => ipcRenderer.invoke('companion:save-card', dataUrl),
  copyShareCard: dataUrl => ipcRenderer.invoke('companion:copy-card', dataUrl),
  copyLetter: text => ipcRenderer.invoke('companion:copy-letter', text),
  onLetterReady: callback => ipcRenderer.on('companion:letter-ready', (_, value) => callback(value)),
  onPeek: callback => ipcRenderer.on('window:peek', (_, value) => callback(value))
});
